site_name: ribomala
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API Reference: api.md

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstrings_style: numpy
            docstring_section_style: table
            paths:
              - ./ribomala

theme:
  name: material
  features:
    - content.code.copy
  palette:
    
    # Palette toggle for dark mode
  - scheme: slate
    primary: amber
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    # Palette toggle for light mode
  - scheme: default
    primary: deep purple
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
